package com.education.outcome.utils;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.education.entity.LearningEvaluate;
import com.education.entity.StudentProfile;
import com.education.outcome.service.LearningEvaluateService;
import com.education.user.service.StudentProfileService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 评估模块定时任务
 * 1. 每日凌晨自动生成学习评估报告（近7天有画像更新的用户）
 * 2. 同步最新评估结果到学生画像
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class AssessmentScheduleTask {

    private final LearningEvaluateService learningEvaluateService;
    private final StudentProfileService studentProfileService;

    /**
     * 每日凌晨2点执行：为近7天有画像更新的用户自动生成评估报告
     */
    @Scheduled(cron = "0 0 2 * * ?")
    public void autoGenerateDailyAssessment() {
        log.info("开始执行每日学习评估任务，时间：{}", LocalDateTime.now());
        try {
            // 查询近7天有更新画像的用户（作为"活跃用户"的代理指标）
            LocalDateTime sevenDaysAgo = LocalDateTime.now().minusDays(7);
            LambdaQueryWrapper<StudentProfile> wrapper = new LambdaQueryWrapper<>();
            wrapper.ge(StudentProfile::getUpdateTime, sevenDaysAgo);
            List<StudentProfile> activeProfiles = studentProfileService.list(wrapper);

            int successCount = 0;
            for (StudentProfile profile : activeProfiles) {
                try {
                    // 生成近7天的全模块评估报告
                    learningEvaluateService.generateReport(
                            null, // 不指定路径：评估整体学习效果
                            List.of("learningTime", "answer", "video", "path")
                    );
                    successCount++;
                    log.info("用户{}每日评估报告生成成功", profile.getUserId());
                } catch (Exception e) {
                    log.error("用户{}评估报告生成失败", profile.getUserId(), e);
                    // 异常不中断批量任务
                }
            }
            log.info("每日学习评估任务执行完成，共处理{}个用户，成功{}个", activeProfiles.size(), successCount);
        } catch (Exception e) {
            log.error("每日学习评估任务执行异常", e);
        }
    }

    /**
     * 每小时同步最新评估结果到学生画像（标记更新场景）
     * 使用 fixedDelay 避免执行重叠
     */
    @Scheduled(fixedDelay = 3600000, initialDelay = 60000) // 延迟1分钟启动，每次间隔1小时
    public void syncAssessmentToProfile() {
        log.info("开始同步评估结果到学生画像，时间：{}", LocalDateTime.now());
        try {
            // 获取近1小时生成的评估报告
            LocalDateTime oneHourAgo = LocalDateTime.now().minusHours(1);
            LambdaQueryWrapper<LearningEvaluate> wrapper = new LambdaQueryWrapper<>();
            wrapper.ge(LearningEvaluate::getCreateTime, oneHourAgo);
            List<LearningEvaluate> recentEvaluates = learningEvaluateService.list(wrapper);

            int syncCount = 0;
            for (LearningEvaluate evaluate : recentEvaluates) {
                try {
                    StudentProfile profile = studentProfileService.getById(
                            getProfileIdByUserId(evaluate.getUserId()));
                    if (profile != null) {
                        profile.setUpdateScene("定时同步评估");
                        studentProfileService.saveOrUpdateProfile(profile);
                        syncCount++;
                    }
                } catch (Exception e) {
                    log.warn("同步用户{}评估结果到画像失败", evaluate.getUserId(), e);
                }
            }
            log.info("同步评估结果到画像完成，共处理{}条记录，成功{}条", recentEvaluates.size(), syncCount);
        } catch (Exception e) {
            log.error("同步评估结果到画像异常", e);
        }
    }

    /**
     * 根据userId查询profile的id
     */
    private Long getProfileIdByUserId(Long userId) {
        LambdaQueryWrapper<StudentProfile> wrapper = new LambdaQueryWrapper<>();
        wrapper.eq(StudentProfile::getUserId, userId).select(StudentProfile::getId);
        StudentProfile profile = studentProfileService.getOne(wrapper);
        return profile != null ? profile.getId() : null;
    }
}
